#!/bin/sh

#author: jiqing
#remove important file safely.
#version: 1.0
#update: 2009-03-31

if test ! -f $1
then
    echo "There is no file \"$1\"."
    exit 1
else
    echo "Do you want to delete \"$1\"?"
    read choice

    if test $choice = y
    then
        rm $1
        echo "\"$1\" is deleted."
    else
        echo "you gave up."
    fi
fi

exit 0
