/* addClientLib.cpp
   Generated by gSOAP 2.8.17r from add.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

/** Use this file in your project build instead of the two files addC.cpp and addClient.cpp. This hides the serializer functions and avoids linking problems when linking multiple clients and servers. */

#ifndef WITH_NOGLOBAL
#define WITH_NOGLOBAL
#endif
#define SOAP_FMAC3 static
#include "addC.cpp"
#include "addClient.cpp"

/* End of addClientLib.cpp */
