PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE heroes (name varchar, race varchar, skill1 varchar, skill2 varchar, skill3 varchar, superskill varchar);
INSERT INTO "heroes" VALUES('大魔法师','人族','水元素','暴风雪','辉煌光环','时空传送');
INSERT INTO "heroes" VALUES('山丘之王','人族','风暴之锤','雷霆一击','重击','天神下凡');
INSERT INTO "heroes" VALUES('血魔法师','人族','炎击','放逐','吸魔','火凤凰');
INSERT INTO "heroes" VALUES('圣骑士','人族','圣光','圣盾','神圣光环','复活');
INSERT INTO "heroes" VALUES('剑圣','兽族','疾风步','镜像','致命一击','剑刃风暴');
INSERT INTO "heroes" VALUES('先知','兽族','远视','闪电链','幽灵狼','地震');
INSERT INTO "heroes" VALUES('牛头人酋长','兽族','冲击波','战争践踏','耐力光环','重生');
INSERT INTO "heroes" VALUES('暗影猎手','兽族','治疗波','妖术','毒蛇守卫','巫毒');
INSERT INTO "heroes" VALUES('恶魔猎手','精灵族','法力燃烧','献祭','躲避','蜕变恶魔');
INSERT INTO "heroes" VALUES('丛林守护者','精灵族','缠绕','自然之力','荆棘光环','宁静之雨');
INSERT INTO "heroes" VALUES('月之女祭司','精灵族','侦查','灼热之箭','强击光环','流行雨');
INSERT INTO "heroes" VALUES('守望者','精灵族','刀扇','闪耀','暗影突袭','复仇天神');
INSERT INTO "heroes" VALUES('死亡骑士','亡灵族','死亡缠绕','死亡契约','邪恶光环','操纵死尸');
INSERT INTO "heroes" VALUES('恐惧魔王','亡灵族','腐臭蜂群','睡眠','吸血光环','地狱火');
INSERT INTO "heroes" VALUES('巫妖','亡灵族','霜冻新星','霜冻护甲','黑暗仪式','死亡凋零');
INSERT INTO "heroes" VALUES('地穴领主','亡灵族','穿刺','刺盾','腐蚀甲虫','蝗群');
COMMIT;
